### ISSUE TITLE
Problème trouvé

### ISSUE THREAD

**Issue by RobinPetit** [kymogram/server-client#1]
J'ai trouvé le problème : à l'endroit où ça plante, la valeur de IAPlay est aberrante parce que tu ne reçois pas le coup joué par l'adversaire mais une chaine de caractère te disant que tu as perdu. En réalité, si tu regardes les tours de boucles faits par le clients et ceux faits par le serveur, tu n'es pas du tout cohérent : le serveur fait plein de tours alors qu'il ne devrait pas.

**Comment by RobinPetit** [comment]
C'est donc lié à la remarque que j'ai faite sur les accolades nécessaires dans le client

**Comment by RobinPetit** [comment]
De plus, ton client envoie un entier pour dire quelle position est visée alors que ton client récupère un char. Ce qui fait que tu mets 4 bytes dans la communication et que le serveur ne les lit qu'un à la fois. C'est pour ça que les tours de boucle sont si incohérents.

**Comment by RobinPetit** [comment]
Ce qui laisse encore un SEGFAULT mais qui sera à mon avis **BEAUCOUPPPPPPP** plus simple à trouver que ce p'tit con là. ^^

**Comment by RobinPetit** [comment]
Pour trouver l'erreur, j'ai quand même dû flusher 32 bits par 32 bits le socket jusqu'à ce que je me rende compte que le premier de tous les 8 bits était à 0 quasi tout le temps ce qui faisait fort penser à un encodage ASCII... Donc que c'étaient des caractères... Puis j'ai fait un script qui récupérait ces p*tains de nombres et qui les convertissait en char pour voir ce que ça donnait, mais c'était affiché "snad el oséderdr"...

**Comment by kymogram** [comment]
J'ai rajouter les accolades qui étaient manquante dans le SERVER mais je n'ai pas trouvé de problème d'accolade dans le client :/ j'ai changé le char en int pour la position que je recevais, mais ça faire encore un segfault au même endroit :(

**Comment by kymogram** [comment]
merci pour avoir prit autant de temps en tout cas :D

**Comment by RobinPetit** [comment]
Arrangé
